export const firebaseConfig = {
  apiKey: 'INSERT YOUR FIREBASE CREDENTIALS HERE',
  authDomain: 'INSERT YOUR FIREBASE CREDENTIALS HERE',
  databaseURL: 'INSERT YOUR FIREBASE CREDENTIALS HERE',
  projectId: 'INSERT YOUR FIREBASE CREDENTIALS HERE',
  storageBucket: 'INSERT YOUR FIREBASE CREDENTIALS HERE',
  messagingSenderId: 'INSERT YOUR FIREBASE CREDENTIALS HERE'
};
